- name: Complete V2Ray and NGINX Setup
  hosts: all
  become: true
  vars_files:
    - vars.yml  
  tasks:
    # Install required packages
    - name: Install NGINX, Certbot, zip, unzip, curl
      apt:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx  # Certbot plugin for NGINX
          - zip
          - unzip
          - curl
        state: latest
        update_cache: true

    # NGINX is started before obtaining SSL
    - name: Ensure NGINX is running
      systemd:
        name: nginx
        state: started
        enabled: true

    # Obtain Let's Encrypt SSL certificate
    - name: Obtain SSL certificate with Certbot
      shell: |
        certbot --nginx -d "{{ domain_name }}" --non-interactive --agree-tos -m "{{ admin_email }}"
      args:
        creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      notify:
        - reload nginx

    # Install V2Ray using the official install script
    - name: Install V2Ray Core using the official script
      shell: |
        bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)
      args:
        creates: /usr/local/bin/v2ray

    # Ensure V2Ray service is enabled and running
    - name: Enable and start V2Ray service
      systemd:
        name: "{{ v2ray_service_name }}"
        state: started
        enabled: true

    # Generate a new UUID
    - name: Generate a UUID for V2Ray
      command: uuidgen
      register: uuid_output

    # Ensure required directories exist
    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      with_items:
        - "{{ qr_code_output_dir }}"

    # Create V2Ray configuration file
    - name: Create V2Ray configuration file
      copy:
        dest: "{{ v2ray_config_path }}"
        content: |
          {
            "log": {
              "loglevel": "info"
            },
            "inbounds": [
              {
                "port": {{ v2ray_port }},
                "protocol": "vmess",
                "settings": {
                  "clients": [
                    {
                      "id": "{{ uuid_output.stdout }}",
                      "alterId": 0
                    }
                  ]
                },
                "streamSettings": {
                  "network": "ws",
                  "wsSettings": {
                    "path": "/proxy/{{ v2ray_port }}"
                  }
                }
              }
            ],
            "outbounds": [
              {
                "protocol": "freedom",
                "settings": {}
              }
            ]
          }
      owner: root
      group: root
      mode: '0644'
      notify:
        - restart v2ray

    # Replace in NGINX configuration with domain_name
    - name: Replace domain_name in NGINX configuration
      template:
        src: ./default.j2  # Jinja2 template with placeholders
        dest: "{{ nginx_sites_enabled }}"
        owner: root
        group: root
        mode: '0644'
      notify:
        - reload nginx

    # Deploy custom scripts
    - name: Deploy add_connection.sh script
      copy:
        src: ./add_connection.sh
        dest: /usr/local/bin/add_connection.sh
        owner: root
        group: root
        mode: '0755'

    - name: Deploy generate_qr.sh script
      copy:
        src: ./generate_qr.sh
        dest: /usr/local/bin/generate_qr.sh
        owner: root
        group: root
        mode: '0755'

    # Step 10: Ensure NGINX is enabled and running
    - name: Start and enable NGINX
      systemd:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: restart v2ray
      systemd:
        name: v2ray
        state: restarted

    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
